services:

  web:
  
    image: 6e4a93453d4e42e757da010b34fc20fc4b53be78c253b6be688451af680558a7:latest
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile 
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data